// ── Changelog data ────────────────────────────────────────────────────────────
// Pure data — no JSX. Consumed by AboutVersionHistory.

export const CHANGELOG = [
  {
    version: "v4.7.1",
    title: "Security Score 100 & Login Code Display Fix",
    date: "2026-07-16",
    accent: "#dc2626",
    changes: [
      "TOTP security score corrected to 100/100 — previously capped at 92 even when the authenticator app was fully active and protecting the account",
      "Security fix: the rotating 6-digit code is no longer displayed on the login verification page — showing it on the same screen as the entry field defeated the purpose of two-factor authentication",
      "The login TOTP step now shows a hint card instead: 'Open the app on your trusted device → My Profile → Security to view your current code'",
    ],
  },
  {
    version: "v4.8.0",
    title: "2FA Security Upgrade — QR Codes, Replay Protection & Standard 30-Second TOTP",
    date: "2026-07-16",
    accent: "#059669",
    changes: [
      "TOTP period corrected to 30 seconds (RFC 6238 standard) — Google Authenticator, Authy, and Microsoft Authenticator all hardcode 30 s and silently ignored the previous 120-second period, making codes permanently invalid in those apps",
      "QR code export restored: scan with Google Authenticator, Authy, or any TOTP app via the QR image; manual-entry secret also available with reveal/copy",
      "New: re-fetch QR code and secret at any time (e.g. to transfer to a new phone) without disabling and re-enabling 2FA",
      "New: generate a fresh set of backup codes with password confirmation — no need to disable and re-enable 2FA",
      "TOTP replay protection: each 30-second code can only be submitted once; a second submission in the same window is rejected",
      "Clock-drift tolerance: codes ±30 seconds from your phone's clock are accepted",
      "Profile 2FA section redesigned with QR image, health bar for remaining backup codes, and regenerate button",
      "Mid-login first-time enrollment now shows the QR inline so you can scan with your app before entering the confirmation code",
    ],
  },
  {
    version: "v4.7.0",
    title: "Built-in Authenticator — Live Code, No QR, No External App",
    date: "2026-07-16",
    accent: "#7c3aed",
    changes: [
      "Two-factor authentication no longer requires scanning a QR code or installing Google Authenticator or Authy — the app generates and displays your 6-digit code directly in a live card",
      "A rotating code card with a countdown ring appears on your profile and during login — read the code, type it in, done",
      "Enabling authenticator 2FA is now a single step: press Enable → see your live code → confirm it",
      "(Superseded by v4.8.0 — the 120-second code period introduced here was incompatible with external authenticator apps)",
    ],
  },
  {
    version: "v4.6.0",
    title: "Login-Time 2FA Method Choice",
    date: "2026-07-15",
    accent: "#0891b2",
    changes: [
      "The post-login verification screen now lets you choose your method — Email OTP or Authenticator App — at login time, not just at setup time",
      "Email OTP resend now has a 120-second cooldown to prevent accidental double-sends",
      "First-time authenticator enrollment can be completed right from the login verification screen — no separate trip to profile settings needed",
      "New backend endpoints: POST /auth/2fa/switch-method (switch method / resend OTP) and POST /auth/2fa/setup-totp-pending (start TOTP enrollment mid-login)",
    ],
  },
  {
    version: "v4.5.1",
    title: "File Manager Permission — Real Granted/Denied Signal",
    date: "2026-07-15",
    accent: "#d97706",
    changes: [
      "File Manager permission now behaves like Location and Notifications — picking a file counts as Allowed, cancelling the picker counts as Denied, instead of always showing as granted",
      "Uses the browser's File System Access API on Chrome/Edge/Opera to detect a real cancel; Safari/Firefox fall back to the previous any-interaction-counts-as-granted behavior since those browsers give no cancel signal",
      "10-second safety timeout still applies so the step can never leave Continue stuck",
    ],
  },
  {
    version: "v4.5.0",
    title: "Permission Card Redesign — File Manager Access & Continue Fix",
    date: "2026-07-15",
    accent: "#4f46e5",
    changes: [
      "The first-login permissions card was redesigned as a clean two-step modal — each permission now shows live status (Requesting… → Allowed/Denied) as it's requested",
      "Added a new File Manager permission step alongside Location and Notifications — opens the native photo/file picker so receipt uploads and exports have a clear, visible consent step",
      "Fixed a bug where the Continue button could stay stuck and unclickable if a permission prompt was blocked or never responded — every permission request now safely times out after 10 seconds so onboarding always completes",
    ],
  },
  {
    version: "v4.4.0",
    title: "First-Login Permissions, 2FA & Single-Device Enforcement",
    date: "2026-07-15",
    accent: "#dc2626",
    changes: [
      "First-time login now walks new users through a one-time, non-skippable notification and file-access permission flow before reaching the dashboard",
      "Two-factor authentication is available for every account — choose an authenticator app (TOTP, with QR code) or email OTP, with 8 one-time backup codes if you lose access to both",
      "Signing in from a new or unrecognized device now requires a verification code before access is granted, and you can mark a device as trusted for 30 days to skip future checks",
      "Only one device can be actively signed in at a time — logging in elsewhere signs out the previous session automatically",
      "Manage recognized devices from your profile — see last-active time and location, and forget any device (or all of them) remotely",
      "Failed sign-in attempts, 2FA challenges, and device verification events are now recorded to a dedicated security log for auditing",
    ],
  },
  {
    version: "v4.3.2",
    title: "Optimization Audit & Measurements",
    date: "2026-07-14",
    accent: "#7c3aed",
    changes: [
      "Measured real response times under load instead of estimating — dashboard and admin pages respond in ~150ms at 50 concurrent users",
      "Added two missing database indexes so login and service lookups stay fast as data grows",
      "Confirmed no other upload path has the same image-size issue the profile photo fix addressed",
    ],
  },
  {
    version: "v4.3.1",
    title: "Performance Pass: Bundle Size & Avatar Compression",
    date: "2026-07-14",
    accent: "#16a34a",
    changes: [
      "Backend server bundle cut by 60% (6.5MB → 2.6MB) by trimming duplicated dependency code out of the build",
      "Profile photos are now automatically resized and compressed on upload — faster to load everywhere they appear, no visible quality loss at avatar size",
    ],
  },
  {
    version: "v4.3.1",
    title: "Config & Maintenance Fixes",
    date: "2026-07-14",
    accent: "#0891b2",
    changes: [
      "/health now reports the real app version read from package.json, instead of a hardcoded string that had drifted stale",
      "Removed a hardcoded personal email fallback for the VAPID push contact — falls back to a generic placeholder; the real address comes from the VAPID_EMAIL setting",
      "The geoip country/city database now refreshes automatically once a week and hot-reloads without a server restart",
    ],
  },
  {
    version: "v4.3.0",
    title: "Security Hardening, Input Validation & Database Integrity",
    date: "2026-07-14",
    accent: "#dc2626",
    changes: [
      // Data integrity
      "Ledger POST now runs inside a single DB transaction — balance update, receipt counter increment, ledger insert, and receipt-token write-back are all atomic; no partial ledger rows possible on mid-write failure",
      "AEPS session ownership check fixed from `if (session && session.createdBy !== userId)` to `if (!session || ...)` — null/orphaned session no longer bypasses the guard",
      "PDF and SMS workers now throw on failure instead of silently completing — failed jobs reach the BullMQ dead-letter queue and are retryable",
      // Security
      "Rate limiter added to GET /api/geo — previously unlimited; now capped at 30 req/min per IP",
      "CORS_ORIGIN missing in production now throws at startup instead of silently falling back to localhost:5000",
      "Dev loopback bypass in rate limiter now compares req.socket?.remoteAddress (real TCP peer, not spoofable) instead of req.ip (X-Forwarded-For, forgeable)",
      "VAPID key rotation endpoint no longer writes to process.env — correct for multi-instance deployments where env writes are per-process only",
      // Logic fixes
      "Ledger summary periods (today, yesterday, week, month) now use IST calendar dates — UTC was shifting the window by up to 5h30m for evening transactions",
      "Large-transaction notification threshold now reads from the settings table key `largeTransactionThreshold` (cached 30 s) instead of a hardcoded ₹10,000 — configurable without a deploy",
      "Large-transaction notification failures now log at WARN level instead of being silently swallowed by `.catch(() => {})`",
      "Session default maxAge aligned to 8 h in express-session to match login.ts non-remember-me override — was 24 h, causing inconsistency",
      "Receipt export ZIP: archive error handler now branches on res.headersSent — sends JSON 500 before streaming starts, destroys socket after (prevents silently-corrupt ZIP files)",
      "Receipt export ZIP: client-disconnect abort flag (`req.on('close')`) stops the PDF generation loop immediately — no wasted CPU for cancelled downloads",
      // Input validation
      "Zod schemas added to all admin receipt-export endpoints: startDate/endDate validated as ISO calendar dates (z.string().date()), userId coerced to positive int, receiptNumbers charset-validated, month range 1-12 enforced, startDate ≤ endDate cross-field check",
      "Receipt token format validated before any DB query — must be a UUID v4 or a three-segment JWT (base64url); arbitrary strings return 400 immediately",
      // Frontend
      "Ledger entry form calls form.reset() after successful create and offline-save — stale values no longer persist when the dialog reopens",
      "Udhari Add Customer dialog resets form state on every close (success or cancel) via useEffect — previous name/mobile/address no longer reappears",
      "Registration form clears all fields and OTP digits before navigating to /login — sensitive values (password, mobile) are removed from React state",
      "ShareTargetHandler useEffect includes setLocation in dependency array — stale closure risk eliminated",
      // Schema / DB
      "5 missing foreign keys added to live database: ledger.created_by → users RESTRICT, audit_logs.user_id → users CASCADE, aeps_daily.created_by → users RESTRICT, broadcast_logs.sent_by → users RESTRICT, password_reset_tokens.user_id → users CASCADE",
    ],
  },
  {
    version: "Infra",
    title: "Redis Connected, Rate-Limiter Fix & CORS Update",
    date: "2026-07-14",
    accent: "#0b2c60",
    changes: [
      "Upstash Redis fully connected — UPSTASH_REDIS_REST_URL / UPSTASH_REDIS_REST_TOKEN / REDIS_URL added as secrets; CACHE_BACKEND switched back to redis; all three servers confirmed healthy",
      "Rate-limiter Redis bridge fixed — app.ts was supplying the @upstash/redis REST client to rate-limit-redis, which expects an ioredis-compatible sendCommand interface; swapped to ioredis (REDIS_URL) so all four rate limiters initialise cleanly",
      "Worker Server connected — all four BullMQ workers (notifications, emails, PDF, SMS) running on Upstash Redis via ioredis",
      "CORS_ORIGIN updated to current Replit dev domain (sisko.replit.dev); verified via OPTIONS preflight — API returns correct Access-Control-Allow-Origin header",
    ],
  },
  {
    version: "v4.2.0",
    title: "Running Balance, CDN Headers & Test Coverage",
    date: "2026-07-14",
    accent: "#6366f1",
    changes: [
      "users.ledger_balance — new maintained NUMERIC column updated atomically on every ledger write; POST /ledger is now O(1) regardless of history length instead of doing a full SUM() scan",
      "Dashboard currentBalance now reads from users.ledger_balance (single primary-key lookup) instead of an all-time aggregate over every ledger row — sub-millisecond on any dataset",
      "GET /api/ledger/balance uses a single LEFT JOIN so balance comes from the authoritative maintained column while totalCredits/totalDebits still come from SUM for the stats display",
      "Cache-Control headers added: receipt-verify endpoints get public, max-age=60, stale-while-revalidate=300; health and setup-status endpoints get no-store",
      "Test suite expanded to 70 tests: 6 new asyncHandler tests (error forwarding, type preservation) and 8 new query-cache tests (hit/miss, TTL expiry, falsy values, prefix invalidation)",
    ],
  },
  {
    version: "v4.1.2",
    title: "Security & Type-Safety Hardening",
    date: "2026-07-13",
    accent: "#10b981",
    changes: [
      "asyncHandler utility wraps all 116 async route handlers across 32 files — unhandled promise rejections now reach Express's error handler instead of hanging the client connection",
      "req.session as any casts removed from admin.ts — replaced with direct req.session.userId using the existing SessionData augmentation",
      "any[] type annotations removed from aeps/transactions.ts sessionWhere and txWhere — TypeScript now infers correct Drizzle SQL condition types",
      "QueryClient staleTime: 5 min + refetchOnWindowFocus: false global defaults confirmed applied to all 64 query hooks",
    ],
  },
  {
    version: "v4.1.1",
    title: "Worker Server — Async Background Processing",
    date: "2026-07-13",
    accent: "#10b981",
    changes: [
      "New @workspace/worker-server (port 8081) — push notifications, email sending, PDF generation, and SMS now run as isolated BullMQ background jobs instead of blocking the main API",
      "API responses return instantly — the main server no longer waits on SMTP delivery or web-push round-trips before sending a response to the client",
      "Graceful fallback: when REDIS_URL is not configured, all jobs execute directly in-process so nothing breaks in development or simple deployments",
      "3 retries with exponential backoff on both email and notification workers — transient SMTP failures or push delivery hiccups auto-recover without manual intervention",
      "pm2.config.js added to root — api-server runs in cluster mode (all CPUs), worker-server in fork mode (1 instance handles concurrency internally via BullMQ)",
    ],
  },
  {
    version: "v4.0.2",
    title: "Image & Loader Polish",
    date: "2026-07-13",
    accent: "#f97316",
    changes: [
      "loading=\"lazy\" added to remaining non-critical images: layout.tsx nav avatars (×2) and AppLogo in sidebar — splash screen, page-skeleton, and LoginLogo intentionally kept eager (first-paint-critical)",
      "GET /admin/users/appeals capped at .limit(500) — the last unbounded list query on the performance checklist",
      "sahu-logo-glow.png deleted from public/ — file had zero references in the codebase; 175 KB removed from the build output",
      "EagerPreloader upgraded from setTimeout(3000) to requestIdleCallback(preload, { timeout: 5000 }) — chunk preloading now fires when the browser is genuinely idle; on slow connections it naturally waits longer; falls back to setTimeout(3000) on older Safari / iOS < 16",
    ],
  },
  {
    version: "v4.0.1",
    title: "Redis Rate Limiting & Multi-Instance Readiness",
    date: "2026-07-13",
    accent: "#f97316",
    changes: [
      "Installed rate-limit-redis — all 4 rate limiters (general, login, auth-write, otp-verify) now use a shared Upstash Redis store when CACHE_BACKEND=redis, so per-IP counters are enforced across all worker processes; falls back to in-process MemoryStore for single-instance/dev deployments",
      "Redis key prefixes namespaced (rl:general:, rl:login:, rl:auth-write:, rl:otp-verify:) — rate-limit keys never collide with query-cache or session-cache keys in the same Redis database",
      "Server logs 'Rate limiter: using shared Redis store' or '…MemoryStore' at boot — active mode is immediately visible in the logs",
      "Added MULTI_INSTANCE_SETUP.md — full guide covering PM2 cluster mode, Node.js cluster module, Replit Deployments scaling, readiness checklist, and connection-pool tuning",
    ],
  },
  {
    version: "v4.0.0",
    title: "Full-Stack Performance Audit",
    date: "2026-07-12",
    accent: "#f97316",
    changes: [
      "8 new API endpoints now cache-backed with 5s TTL + immediate write-invalidation: GET /aeps/session, /aeps/transactions, /admin/aeps-overview, /udhari/summary, /udhari/customers, /udhari/customers/:id, /udhari/customers/:id/entries, /users — previously all hit the database on every request",
      "6 new database indexes pushed: users.role, users.status, aeps_transactions.dailyId / type / createdAt, push_subscriptions.userId, password_reset_tokens.userId — fixes full-table scans on admin, AePS, push, and password-reset queries",
      "React Query cache persister switched from synchronous sessionStorage (createSyncStoragePersister) to async IndexedDB via idb-keyval (createAsyncStoragePersister) — eliminates the main-thread block that occurred after every mutation",
      "EagerPreloader deferred 3 seconds post-login — chunk preloading no longer races with the first real API calls (dashboard stats, session auth)",
      "Unbounded list queries capped: .limit(500) on Udhari customers and entries routes",
      "loading=\"lazy\" added to off-screen images on About and Download App pages",
    ],
  },
  {
    version: "v3.5.10",
    title: "Navigation Performance — Instant Page Switching",
    date: "2026-07-12",
    accent: "#f97316",
    changes: [
      "Removed AnimatePresence mode=\"wait\" — pages now cross-fade simultaneously instead of waiting for the exit animation to complete before the enter animation starts; perceived navigation delay cut from ~440ms to ~150ms",
      "Extracted LiveClock as an isolated React.memo component — the 1-second clock tick now re-renders only a single <span>, not the entire Layout tree; eliminates up to 60 unnecessary Layout reconciliations per minute",
      "Removed y-translation from page transition animation — opacity-only fade avoids layout recalculation on every animation frame; transition easing simplified to easeOut",
      "Animation duration reduced from scaleDuration(220) to scaleDuration(150) — shorter duration further reduces the time between a tap and the new page being fully visible",
    ],
  },
  {
    version: "v3.5.9",
    title: "Redis Cache Live, i18n Fixes & Build Hardening",
    date: "2026-07-12",
    accent: "#f97316",
    changes: [
      "Upstash Redis activated as the live cache backend (CACHE_BACKEND=redis) — dashboard stats, session/role lookups, and report queries now survive server restarts and are shared across instances; fails open to a DB re-query if Redis is unavailable",
      "5 missing i18n keys added to all 3 locales (en/hi/or): common.platform (register pages), udhari.customer.settled, udhari.customer.edit_entry, udhari.customer.desc_gave, udhari.customer.desc_got — all Udhari customer and register page strings now translate correctly in Hindi and Odia",
      "@opentelemetry/api pinned via pnpm-workspace.yaml overrides — prevents future @sentry/node upgrades from silently creating a dual drizzle-orm resolution; pre-build checkDrizzlePeerSingleton() in build.mjs fails fast with a remediation guide if the problem recurs",
      "Stale 'Build API' workflow references permanently removed from package.json dev script and replit.md — API Server already builds before starting, the duplicate was confusing",
    ],
  },
  {
    version: "v3.5.8",
    title: "Reports & Receipt Export Page Modularization",
    date: "2026-07-12",
    accent: "#f97316",
    changes: [
      "reports.tsx (1301 lines) split into hooks/useReports.ts (filter state, data hooks, derived values) and 3 components — ReportSummaryCards, ReportChart, ReportFilters — with the page kept as a thin orchestrator",
      "receipt-export.tsx (1219 lines) split into hooks/useReceiptExport.ts (all state + buildParams() shared by all 3 bulk-export endpoints), types.ts (interfaces + constants), ExportFilters.tsx, and ReceiptPreviewList.tsx",
      "No behavior change — routes, API calls, data-testids, and visual output are all identical; verified with tsc --noEmit across all workspace projects and a clean browser render",
    ],
  },
  {
    version: "v3.5.7",
    title: "Pluggable Cache Backend & Load-Test Baseline",
    date: "2026-07-12",
    accent: "#f97316",
    changes: [
      "Query cache and session/role cache now sit behind a swappable backend (process-local memory by default, optional Upstash Redis via CACHE_BACKEND=redis) — groundwork for running more than one API instance; default behavior and 5s TTLs are unchanged",
      "Documented read-replica routing guidance, correcting an earlier assumption — this app runs on Replit's built-in Postgres, which has no read-replica option today, so this is forward-looking guidance rather than an active feature",
      "Re-ran the concurrent-user load test at higher connection counts (50/100/200) against disposable data with read-heavy and write-heavy mixes — findings recorded in LOADTEST_FINDINGS.md, no architecture changes made based on results in this pass",
    ],
  },
  {
    version: "v3.5.6",
    title: "Documentation Consolidation, i18n Completion & CDN Setup Guide",
    date: "2026-07-11",
    accent: "#0b2c60",
    changes: [
      "9 parallel documentation files consolidated into 4 canonical files plus short pointers — prevents future changelog drift",
      "Filled the one missing Hindi/Odia translation key (nav.admin) — all 793 keys now complete in all 3 languages",
      "Wrote a Cloudflare CDN setup guide (CDN_SETUP.md) for the existing single-origin deployment — documentation only, not yet provisioned",
    ],
  },
  {
    version: "v3.5.5",
    title: "Tests, Error Tracking & Bundle Audit",
    date: "2026-07-11",
    accent: "#f97316",
    changes: [
      "42 automated Vitest tests cover ledger balance math, receipt-number generation (CSC-YYYY-NNNN), and all auth/session middleware (requireAuth, requirePermission, requireRole, lockout, session durations)",
      "Sentry APM integrated server-side (@sentry/node) and client-side (@sentry/react) — no-ops when SENTRY_DSN / VITE_SENTRY_DSN env vars are absent; no PII reaches Sentry",
      "React ErrorBoundary wraps the entire app — unexpected render crashes now show a branded recovery screen instead of a blank page",
      "Build audit confirmed recharts (420 KB), jsPDF (386 KB), and html2canvas (201 KB) are separate lazy chunks; main bundle is 438 KB (under 500 KB threshold)",
    ],
  },
  {
    version: "v3.5.4",
    title: "Ledger Page Modularization",
    date: "2026-07-11",
    accent: "#0b2c60",
    changes: [
      "Split the 1652-line ledger.tsx into a thin orchestrator plus hooks/useLedger.ts and 3 focused components",
      "No behavior change — routes, API calls, data-testids, and visual output are all unchanged",
      "Verified with a clean typecheck across all workspace projects and an authenticated end-to-end curl smoke test",
    ],
  },
  {
    version: "v3.5.3",
    title: "Query Caching & Load Testing",
    date: "2026-07-10",
    accent: "#0b2c60",
    changes: [
      "5s TTL query cache in front of dashboard, admin overview, and daily/monthly reports — invalidated on every ledger write",
      "Lightweight APM surrogate: requests over 500ms now log at warn with a slowRequest flag",
      "Real load-test numbers (autocannon): dashboard p50 47ms/p95 272ms, admin overview p50 46ms/p95 251ms, 0 errors at 20 concurrent connections",
    ],
  },
  {
    version: "v3.5.2",
    title: "Asset & Delivery Hardening",
    date: "2026-07-10",
    accent: "#f97316",
    changes: [
      "CSP enabled on the API server (default-src 'none') — was previously fully disabled",
      "Health/setup-status checks now skip the session-store DB lookup entirely",
      "Image optimization pipeline added — static assets ~31% smaller (logo glow: 1.6MB → 144KB)",
      "Production static server rewritten — hashed assets cached 1 year, app shell never cached, fixing a stale-deploy risk",
    ],
  },
  {
    version: "v3.5.1",
    title: "Performance & Scale Hardening",
    date: "2026-07-10",
    accent: "#0b2c60",
    changes: [
      "Fixed N+1 queries on the admin overview page — one batched query instead of per-user queries",
      "Batched bulk writes: ledger balance recalculation, notification inserts, and settings upserts",
      "Database connection pool tuned with explicit max/timeout limits",
      "Session validation cached in-memory (5s TTL), cutting a DB round-trip off most authenticated requests",
    ],
  },
  {
    version: "v3.4.0",
    title: "Receipt Export Layout Refactor",
    date: "2026-07-10",
    accent: "#f97316",
    changes: [
      "Receipt Export page migrated to shared <Layout> — no more duplicate custom header, sidebar, or bottom nav",
      "Desktop: 4-column KPI stat bar → filter row → two-column body (receipt table left, export panel + preview right)",
      "Mobile: top pill tab row (Receipts / By Date / Summary / Export) replaces old fixed bottom nav conflict",
      "TypeScript: added UserOverview interface; removed all unsafe any in users query and map callbacks",
    ],
  },
  {
    version: "v3.3.0",
    title: "Email & Security Hardening",
    date: "2026-07-08",
    accent: "#0b2c60",
    changes: [
      "V2 dark premium email templates — all 7 types with dark gradient card, per-type accent colours, HTML-safe esc() on every dynamic field",
      "OTP email: digit boxes + copy strip; easy tap-to-copy on any email client",
      "SMTP live: Gmail (smtp.gmail.com:587) configured, all transactional emails now deliver",
      "Password policy: 8+ chars, no max, uppercase + lowercase + number + special char",
      "Login lockout tightened to 3 failed attempts → 5-minute lock",
    ],
  },
  {
    version: "v3.2.5",
    title: "Security Upgrade",
    date: "2026-07-06",
    accent: "#0b2c60",
    changes: [
      "Unified password policy applied across registration, reset, profile, and admin flows",
      "Tighter rate limiting on login, register, OTP, and password-reset endpoints",
      "Sensitive fields encrypted at rest with AES-256-GCM",
    ],
  },
  {
    version: "v3.2.0–v3.2.4",
    title: "Performance, Skeletons & Diagnostics",
    date: "2026-07-04–06",
    accent: "#0b2c60",
    changes: [
      "Adaptive animation performance tier (High / Medium / Low) based on CPU, RAM, network, rAF benchmark",
      "All spinners replaced with content-shaped skeletons across every page",
      "Device Performance card on Server Health page showing live FPS and tier",
      "Heap check now uses V8 heap_size_limit (crash ceiling) instead of heapTotal",
    ],
  },
  {
    version: "v3.1.1",
    title: "Receipt Export Redesign",
    date: "2026-07-01",
    accent: "#0b2c60",
    changes: [
      "Receipt Export mobile UI redesigned — fits any screen with height: 100dvh",
      "4-tab bottom nav (Receipts / By Date / Summary / Export) always visible",
      "By Date tab: date range + quick presets + operator filter",
      "Summary tab: 4 colour-coded aggregate stat cards",
    ],
  },
  {
    version: "v3.1.0",
    title: "Backup & Restore",
    date: "2026-06-30",
    accent: "#0b2c60",
    changes: [
      "Backup page redesigned — Minimal Clean UI with 2-column desktop grid",
      "Backup download streams .sql file with Content-Disposition: attachment",
      "Auto-backup scheduler (daily/weekly/custom cron) with configurable retention",
      "Selective table import: replay chosen tables from pg_dump with FK checks disabled",
    ],
  },
  {
    version: "v3.0.0",
    title: "Setup Wizard & SMTP",
    date: "2026-06-25",
    accent: "#0b2c60",
    changes: [
      "Setup Wizard Banner — admin-only banner when secrets missing",
      "GET /api/setup-status public endpoint for secrets readiness check",
      "Automatic DB migration on import via scripts/post-merge.sh",
      "Seed passwords read from ADMIN_PASSWORD / OPERATOR_PASSWORD secrets — never hardcoded",
    ],
  },
  {
    version: "v2.4",
    title: "Udhari Khata",
    date: "2026-06-18",
    accent: "#0b2c60",
    changes: [
      "Full customer credit ledger: You Gave / You Got, WhatsApp reminder, PDF statement",
      "Dashboard Udhari summary card — To Collect / To Pay at a glance",
      "Auto receipt number (CSC-YYYY-NNNN) added to all ledger entries",
    ],
  },
  {
    version: "v2.0",
    title: "PWA & Multi-Device",
    date: "2026-06-13–17",
    accent: "#0b2c60",
    changes: [
      "PWA offline mode: ledger entries queue offline, sync on reconnect",
      "Push notifications via VAPID web-push",
      "Multi-device sessions with device info, browser, OS, IP tracking",
      "Forgot-password: unified 4-step flow (identifier → OTP → new password → success)",
      "Initial release: Ledger, AePS Cash, Reports, Services, Dashboard",
    ],
  },
];
