import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { fmt, fmtDate, type AepsSession } from "@/pages/aeps/aeps.constants";

/**
 * Encapsulates WhatsApp share and PDF generation for an AePS daily session.
 * Extracted from DailyTab to keep that component's render function focused.
 */
export function useAepsExport(session: AepsSession | undefined) {
  const { toast } = useToast();
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [exportLoading, setExportLoading] = useState<"pdf" | "wa" | null>(null);

  const shareAepsWhatsApp = () => {
    if (!session) return;
    setExportLoading("wa");
    const dateLabel = fmtDate(session.date);
    const lines: string[] = [
      `📊 *SAHU CSC — AePS Daily Summary*`,
      `📅 *Date:* ${dateLabel}`,
      ``,
      `💰 *Opening Balance:* ₹${fmt(session.openingBalance)}`,
      ``,
      `📋 *Transactions (${session.transactions.length}):*`,
    ];
    session.transactions.forEach((tx, i) => {
      const arrow = tx.type === "withdrawal" ? "↓" : "↑";
      const label = tx.type === "withdrawal" ? "Withdrawal" : "Deposit";
      lines.push(
        `${i + 1}. ${arrow} ${label} — ${tx.customerName}: ₹${fmt(tx.amount)} (Bal: ₹${fmt(tx.balance)})`
        + (tx.description ? ` [${tx.description}]` : "")
      );
    });
    lines.push(``);
    lines.push(`📊 *Summary:*`);
    lines.push(`↓ Total Withdrawals: ₹${fmt(session.totalWithdrawals)}`);
    lines.push(`↑ Total Deposits:    ₹${fmt(session.totalDeposits)}`);
    lines.push(``);
    lines.push(`${session.currentBalance < 0 ? "⚠️" : "✅"} *Closing Balance: ₹${fmt(session.currentBalance)}*`);
    lines.push(``);
    lines.push(`_Generated by SAHU CSC_`);
    const text = encodeURIComponent(lines.join("\n"));
    window.open(`https://wa.me/?text=${text}`, "_blank", "noopener,noreferrer");
    setShowExportMenu(false);
    setExportLoading(null);
  };

  const generateAepsPDF = async () => {
    if (!session) return;
    setExportLoading("pdf");
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageW = 210;
      const margin = 18;
      const contentW = pageW - margin * 2;
      let y = 20;

      // Header
      doc.setFillColor(11, 44, 96);
      doc.rect(0, 0, pageW, 28, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(255, 255, 255);
      doc.text("SAHU CSC", margin, 12);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text("AePS Daily Summary Report", margin, 19);
      doc.setFontSize(9);
      doc.text(fmtDate(session.date), pageW - margin, 12, { align: "right" });
      y = 36;

      // Summary box
      doc.setFillColor(241, 245, 249);
      doc.roundedRect(margin, y, contentW, 28, 3, 3, "F");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text("OPENING BALANCE", margin + 6, y + 8);
      doc.text("TOTAL WITHDRAWALS", margin + contentW / 3 + 3, y + 8);
      doc.text("TOTAL DEPOSITS", margin + (contentW * 2) / 3 + 3, y + 8);
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(11, 44, 96);
      doc.text(`Rs.${fmt(session.openingBalance)}`, margin + 6, y + 20);
      doc.setTextColor(225, 29, 72);
      doc.text(`Rs.${fmt(session.totalWithdrawals)}`, margin + contentW / 3 + 3, y + 20);
      doc.setTextColor(5, 150, 105);
      doc.text(`Rs.${fmt(session.totalDeposits)}`, margin + (contentW * 2) / 3 + 3, y + 20);
      y += 36;

      // Transactions table header
      doc.setFillColor(11, 44, 96);
      doc.rect(margin, y, contentW, 8, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text("#", margin + 2, y + 5.5);
      doc.text("Time", margin + 8, y + 5.5);
      doc.text("Customer", margin + 28, y + 5.5);
      doc.text("Type", margin + 90, y + 5.5);
      doc.text("Amount", margin + 118, y + 5.5);
      doc.text("Balance", margin + 148, y + 5.5);
      y += 8;

      session.transactions.forEach((tx, i) => {
        if (y > 260) { doc.addPage(); y = 20; }
        const isEven = i % 2 === 0;
        doc.setFillColor(isEven ? 248 : 255, isEven ? 250 : 255, isEven ? 252 : 255);
        doc.rect(margin, y, contentW, 8, "F");
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(71, 85, 105);
        const time = new Date(tx.createdAt).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });
        doc.text(String(i + 1), margin + 2, y + 5.5);
        doc.text(time, margin + 8, y + 5.5);
        const nameShort = tx.customerName.length > 28 ? tx.customerName.slice(0, 26) + "…" : tx.customerName;
        doc.text(nameShort, margin + 28, y + 5.5);
        doc.setTextColor(tx.type === "withdrawal" ? 225 : 5, tx.type === "withdrawal" ? 29 : 150, tx.type === "withdrawal" ? 72 : 105);
        doc.text(tx.type === "withdrawal" ? "Withdrawal" : "Deposit", margin + 90, y + 5.5);
        doc.setTextColor(71, 85, 105);
        doc.text(`Rs.${fmt(tx.amount)}`, margin + 118, y + 5.5);
        doc.text(`Rs.${fmt(tx.balance)}`, margin + 148, y + 5.5);
        y += 8;
      });

      // Closing balance footer
      y += 4;
      const closingColor = session.currentBalance < 0 ? [225, 29, 72] : [5, 150, 105];
      doc.setFillColor(...(closingColor as [number, number, number]));
      doc.rect(margin, y, contentW, 10, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      doc.text("CLOSING BALANCE", margin + 4, y + 7);
      doc.text(`Rs.${fmt(session.currentBalance)}`, pageW - margin - 4, y + 7, { align: "right" });

      const fileName = `AePS-Summary-${session.date}.pdf`;
      doc.save(fileName);
      toast({ title: "PDF downloaded", description: fileName });
      setShowExportMenu(false);
    } catch {
      toast({ title: "Failed to generate PDF", variant: "destructive" });
    } finally {
      setExportLoading(null);
    }
  };

  return { showExportMenu, setShowExportMenu, exportLoading, generateAepsPDF, shareAepsWhatsApp };
}
