import { Router, type IRouter } from "express";
import authRouter from "./auth";
import ledgerRouter from "./ledger";
import servicesRouter from "./services";
import usersRouter from "./users";
import notificationsRouter from "./notifications";
import auditRouter from "./audit";
import settingsRouter from "./settings";
import reportsRouter from "./reports";
import aepsRouter from "./aeps";
import profileRouter from "./profile";
import preferencesRouter from "./preferences";
import dashboardRouter from "./dashboard";
import adminAppealsRouter from "./admin-appeals";
import pushRouter from "./push";
import sessionsRouter from "./sessions";
import adminRouter from "./admin";
import adminRegistrationRouter from "./admin-registration";
import adminSessionsRouter from "./admin-sessions";
import udhariRouter from "./udhari";
import receiptsRouter from "./receipts";
import broadcastRouter from "./broadcast";
import adminReceiptExportRouter from "./admin-receipt-export";

const router: IRouter = Router();

router.use(authRouter);
router.use(profileRouter);
router.use(preferencesRouter);
router.use(ledgerRouter);
router.use(servicesRouter);
router.use(usersRouter);
router.use(notificationsRouter);
router.use(auditRouter);
router.use(settingsRouter);
router.use(reportsRouter);
router.use(dashboardRouter);
router.use(aepsRouter);
router.use(pushRouter);
router.use(sessionsRouter);
router.use(adminRouter);
router.use(adminRegistrationRouter);
router.use(adminAppealsRouter);
router.use(adminSessionsRouter);
router.use(udhariRouter);
router.use(receiptsRouter);
router.use(broadcastRouter);
router.use(adminReceiptExportRouter);

export default router;
