import React from "react";
import { CheckCircle2, Eye, EyeOff, KeyRound, Loader2, Lock, ShieldCheck, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PWD_RULES } from "./loginTypes";

interface Props {
  password: string;
  confirmPassword: string;
  showPassword: boolean;
  showConfirm: boolean;
  serverError: string | null;
  submitting: boolean;
  pwdRulesMet: boolean;
  passwordsMatch: boolean;
  adminResetMode: boolean;
  adminLinkExpired: boolean;
  adminLinkSecondsLeft: number | null;
  onPasswordChange: (value: string) => void;
  onConfirmChange: (value: string) => void;
  onTogglePassword: () => void;
  onToggleConfirm: () => void;
  onSubmit: (e: React.FormEvent) => void;
}

export function NewPasswordForm({
  password,
  confirmPassword,
  showPassword,
  showConfirm,
  serverError,
  submitting,
  pwdRulesMet,
  passwordsMatch,
  adminResetMode,
  adminLinkExpired,
  adminLinkSecondsLeft,
  onPasswordChange,
  onConfirmChange,
  onTogglePassword,
  onToggleConfirm,
  onSubmit,
}: Props) {
  return (
    <>
      <div className="flex flex-col items-center mb-6">
        <div
          className="w-12 h-12 rounded-2xl flex items-center justify-center shadow-sm mb-3"
          style={{ background: "#fef3c7" }}
        >
          <KeyRound className="w-6 h-6 text-amber-500" />
        </div>
        <h2 className="text-gray-900 font-bold text-lg">Set New Password</h2>
        <p className="text-gray-500 text-xs mt-1 text-center max-w-xs">
          {adminResetMode
            ? "Your administrator has granted you a secure reset link. Choose a new password below."
            : "Choose a strong password for your account."}
        </p>
      </div>

      {/* Admin link expired banner */}
      {adminResetMode && adminLinkExpired && (
        <div className="mb-4 rounded-xl border border-red-300 bg-red-50 px-4 py-3 flex items-start gap-2.5 text-xs text-red-800">
          <XCircle className="w-4 h-4 mt-0.5 shrink-0 text-red-500" />
          <div>
            <p className="font-semibold">Reset link has expired</p>
            <p className="mt-0.5 text-red-700">
              This link is no longer valid. Please ask your administrator to generate a new one.
            </p>
          </div>
        </div>
      )}

      {/* Admin link active banner */}
      {adminResetMode && !adminLinkExpired && (
        <div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 flex items-start gap-2.5 text-xs text-blue-800">
          <ShieldCheck className="w-4 h-4 mt-0.5 shrink-0 text-blue-500" />
          <div className="flex-1 min-w-0">
            <p className="font-semibold">Admin-assisted reset</p>
            <p className="mt-0.5 text-blue-700">
              This link was generated by your administrator and can only be used once.
            </p>
            {adminLinkSecondsLeft !== null && (
              <div className="mt-2.5 flex items-center gap-2">
                <div className="flex-1 h-1.5 rounded-full overflow-hidden bg-blue-200">
                  <div
                    className="h-full rounded-full transition-all duration-1000"
                    style={{
                      width: `${Math.min(100, (adminLinkSecondsLeft / 600) * 100)}%`,
                      background:
                        adminLinkSecondsLeft <= 60
                          ? "#ef4444"
                          : adminLinkSecondsLeft <= 120
                          ? "#f97316"
                          : "#2563eb",
                    }}
                  />
                </div>
                <span
                  className="font-black tabular-nums shrink-0 text-sm"
                  style={{
                    color:
                      adminLinkSecondsLeft <= 60
                        ? "#dc2626"
                        : adminLinkSecondsLeft <= 120
                        ? "#ea580c"
                        : "#1d4ed8",
                  }}
                >
                  {String(Math.floor(adminLinkSecondsLeft / 60)).padStart(2, "0")}:
                  {String(adminLinkSecondsLeft % 60).padStart(2, "0")}
                </span>
                <span className="text-blue-500 text-[10px] shrink-0">remaining</span>
              </div>
            )}
          </div>
        </div>
      )}

      <form onSubmit={onSubmit} className="space-y-4">
        {/* New password */}
        <div className="relative">
          <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
          <Input
            type={showPassword ? "text" : "password"}
            placeholder="New password"
            className="pl-10 pr-10 h-11 text-gray-900 placeholder:text-gray-400 border-gray-200 bg-white focus-visible:ring-2 focus-visible:ring-blue-400"
            autoFocus
            autoComplete="new-password"
            value={password}
            onChange={(e) => onPasswordChange(e.target.value)}
          />
          <button
            type="button"
            className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
            onClick={onTogglePassword}
          >
            {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
          </button>
        </div>

        {/* Strength meter */}
        {password && (
          <div className="grid grid-cols-2 gap-1">
            {PWD_RULES.map((r) => (
              <div key={r.label} className="flex items-center gap-1.5 text-[11px]">
                <div
                  className="w-1.5 h-1.5 rounded-full flex-shrink-0"
                  style={{ background: r.test(password) ? "#22c55e" : "#d1d5db" }}
                />
                <span style={{ color: r.test(password) ? "#16a34a" : "#9ca3af" }}>{r.label}</span>
              </div>
            ))}
          </div>
        )}

        {/* Confirm password */}
        <div className="relative">
          <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
          <Input
            type={showConfirm ? "text" : "password"}
            placeholder="Confirm new password"
            className="pl-10 pr-10 h-11 text-gray-900 placeholder:text-gray-400 border-gray-200 bg-white focus-visible:ring-2 focus-visible:ring-blue-400"
            autoComplete="new-password"
            value={confirmPassword}
            onChange={(e) => onConfirmChange(e.target.value)}
          />
          <button
            type="button"
            className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
            onClick={onToggleConfirm}
          >
            {showConfirm ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
          </button>
        </div>

        {confirmPassword && (
          <div className={`flex items-center gap-1.5 text-xs ${passwordsMatch ? "text-green-600" : "text-gray-400"}`}>
            <div className={`w-1.5 h-1.5 rounded-full ${passwordsMatch ? "bg-green-500" : "bg-gray-300"}`} />
            {passwordsMatch ? "Passwords match" : "Passwords do not match yet"}
          </div>
        )}

        {serverError && (
          <div className="flex items-start gap-2 text-xs text-red-600 bg-red-50 border border-red-200 rounded-lg p-2.5">
            <XCircle className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />
            {serverError}
          </div>
        )}

        <Button
          type="submit"
          disabled={submitting || !pwdRulesMet || !passwordsMatch || adminLinkExpired}
          className="w-full h-11 font-bold text-white border-0"
          style={{ background: "linear-gradient(135deg, #1a2560, #0f1a4a)" }}
        >
          {submitting ? (
            <span className="flex items-center gap-2">
              <Loader2 className="w-4 h-4 animate-spin" />
              Saving…
            </span>
          ) : (
            <span className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4" />
              Set New Password
            </span>
          )}
        </Button>
      </form>
    </>
  );
}
