// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ledger-redesign/CommandCenter.tsx": () => import("../components/mockups/ledger-redesign/CommandCenter.tsx"),
  "./components/mockups/ledger-redesign/Current.tsx": () => import("../components/mockups/ledger-redesign/Current.tsx"),
  "./components/mockups/ledger-redesign/MidnightFinance.tsx": () => import("../components/mockups/ledger-redesign/MidnightFinance.tsx"),
  "./components/mockups/ledger-redesign/SplitLedgerBook.tsx": () => import("../components/mockups/ledger-redesign/SplitLedgerBook.tsx"),
  "./components/mockups/ledger-redesign/ToolbarDriven.tsx": () => import("../components/mockups/ledger-redesign/ToolbarDriven.tsx")
};
