// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/addentry/AddEntryForm.tsx": () => import("../components/mockups/addentry/AddEntryForm.tsx"),
  "./components/mockups/aeps-desktop/AePS.tsx": () => import("../components/mockups/aeps-desktop/AePS.tsx"),
  "./components/mockups/aeps/AepsEntryForm.tsx": () => import("../components/mockups/aeps/AepsEntryForm.tsx"),
  "./components/mockups/aeps/AepsPage.tsx": () => import("../components/mockups/aeps/AepsPage.tsx"),
  "./components/mockups/aeps-entry-form/AepsEntry.tsx": () => import("../components/mockups/aeps-entry-form/AepsEntry.tsx"),
  "./components/mockups/aeps-mobile-entry/AepsMobileEntry.tsx": () => import("../components/mockups/aeps-mobile-entry/AepsMobileEntry.tsx"),
  "./components/mockups/aeps-page/AePS.tsx": () => import("../components/mockups/aeps-page/AePS.tsx"),
  "./components/mockups/ledger/LedgerPage.tsx": () => import("../components/mockups/ledger/LedgerPage.tsx"),
  "./components/mockups/ledger-desktop/Ledger.tsx": () => import("../components/mockups/ledger-desktop/Ledger.tsx"),
  "./components/mockups/receipt/ReceiptDesign.tsx": () => import("../components/mockups/receipt/ReceiptDesign.tsx"),
  "./components/mockups/sahu-csc/Desktop.tsx": () => import("../components/mockups/sahu-csc/Desktop.tsx"),
  "./components/mockups/sahu-csc/Login.tsx": () => import("../components/mockups/sahu-csc/Login.tsx"),
  "./components/mockups/sahu-csc/Mobile.tsx": () => import("../components/mockups/sahu-csc/Mobile.tsx"),
  "./components/mockups/sahu-csc/Register.tsx": () => import("../components/mockups/sahu-csc/Register.tsx"),
  "./components/mockups/sahu-csc/Tablet.tsx": () => import("../components/mockups/sahu-csc/Tablet.tsx"),
  "./components/mockups/sahu-header/Minimal.tsx": () => import("../components/mockups/sahu-header/Minimal.tsx"),
  "./components/mockups/sahu-header/MobileNew.tsx": () => import("../components/mockups/sahu-header/MobileNew.tsx"),
  "./components/mockups/sahu-header/Modern.tsx": () => import("../components/mockups/sahu-header/Modern.tsx"),
  "./components/mockups/udhari/UdhariForm.tsx": () => import("../components/mockups/udhari/UdhariForm.tsx"),
  "./components/mockups/udhari-desktop/Udhari.tsx": () => import("../components/mockups/udhari-desktop/Udhari.tsx")
};
