export function V1AdminResetLink() {
  return (
    <div className="min-h-screen bg-[#eef2f7] flex items-center justify-center py-10 px-4 font-sans">
      <div style={{ maxWidth: '560px', width: '100%', backgroundColor: '#ffffff', borderRadius: '18px', overflow: 'hidden', boxShadow: '0 4px 20px rgba(0,0,0,0.08)', fontFamily: 'system-ui, -apple-system, sans-serif' }}>
        <div style={{ backgroundColor: '#0b2c60', padding: '40px 24px', textAlign: 'center', color: '#ffffff' }}>
          <div style={{ display: 'inline-block', width: '56px', height: '56px', borderRadius: '50%', backgroundColor: 'rgba(255,255,255,0.1)', lineHeight: '56px', fontSize: '24px', marginBottom: '16px' }}>🔑</div>
          <div style={{ fontSize: '12px', fontWeight: 600, letterSpacing: '1px', color: 'rgba(255,255,255,0.7)', marginBottom: '12px' }}>PASSWORD RESET LINK</div>
          <div style={{ fontSize: '28px', fontWeight: 700, letterSpacing: '-0.5px' }}>SAHU <span style={{ color: '#f97316' }}>CSC</span></div>
        </div>
        <div style={{ backgroundColor: '#f97316', height: '6px' }}></div>
        
        <div style={{ padding: '36px', color: '#1e293b', fontSize: '16px', lineHeight: '1.6' }}>
          <h1 style={{ fontSize: '22px', fontWeight: 600, color: '#0b2c60', margin: '0 0 16px 0' }}>Hi Meena!</h1>
          <p style={{ margin: '0 0 32px 0' }}>Your administrator has generated a secure, one-time password reset link for your SAHU CSC account (<strong>@meena_op</strong>). Click the button below to set a new password.</p>
          
          <div style={{ textAlign: 'center', margin: '32px 0' }}>
            <a href="#" style={{ display: 'inline-block', backgroundColor: '#f97316', color: '#ffffff', textDecoration: 'none', padding: '16px 32px', borderRadius: '10px', fontSize: '16px', fontWeight: 600, boxShadow: '0 4px 12px rgba(249,115,22,0.3)' }}>
              🔒 Reset My Password
            </a>
          </div>
          
          <div style={{ backgroundColor: '#fff7ed', border: '1px solid rgba(249,115,22,0.3)', borderRadius: '10px', padding: '16px', margin: '32px 0', fontSize: '14px', color: '#9a3412', textAlign: 'center' }}>
            ⚠️ <strong>Expires at 11:30 PM</strong> · This link is single-use and will expire after use or in 2 hours
          </div>
          
          <div style={{ padding: '16px', backgroundColor: '#f8fafc', borderLeft: '4px solid #0b2c60', borderRadius: '0 10px 10px 0', fontSize: '14px', color: '#475569' }}>
            <strong>Security Notice:</strong> This link was generated by your administrator. Do NOT share it with anyone.
          </div>
        </div>
        
        <div style={{ backgroundColor: '#f1f5f9', padding: '24px 36px', textAlign: 'center', fontSize: '12px', color: '#64748b', borderTop: '1px solid #e2e8f0' }}>
          SAHU CSC · Common Service Center · Odisha, India<br/>
          <span style={{ marginTop: '12px', display: 'inline-block' }}>This is an automated message, please do not reply.</span>
        </div>
      </div>
    </div>
  );
}
